---
- name: ensure ~/apps directory is ready
  file: path=~/apps
        state=directory
        recurse=yes

- name: clone ansible
  git: repo=https://github.com/ansible/ansible.git
       dest=~/apps/ansible
       update={{ update_ansible }}

- name: ensure virtualenv for ansible is installed
  shell: PYENV_VERSION=2.7.6 virtualenv ~/apps/ansible/.virtualenv
         creates=~/apps/ansible/.virtualenv/bin/activate

- name: ensure dependencies for ansible is installed
  shell: ~/apps/ansible/.virtualenv/bin/pip install {{ item.name }}
         creates=~/apps/ansible/.virtualenv/lib/python2.7/site-packages/{{ item.creates }}
  with_items:
      - name: paramiko==1.12.2
        creates: paramiko-1.12.0-py2.7.egg-info
      - name: Jinja2==2.7.2
        creates: Jinja2-2.7.2-py2.7.egg-info
      - name: PyYAML==3.10
        creates: PyYAML-3.10-py2.7.egg-info
      - name: httplib2==0.8
        creates: httplib2-0.8-py2.7.egg-info

- name: ensure ansible wrapper is ready
  template: src=_ansible-wrapper
            dest=~/bin/_ansible-wrapper
            mode=0755

- name: ensure ansible binaries are linked
  file: src=~/bin/_ansible-wrapper
        dest=~/bin/{{ item }}
        state=link
  with_items:
    - ansible
    - ansible-playbook
    - ansible-pull
    - ansible-doc
    - ansible-galaxy
