---
- name: ensure tmux is installed - MacOSX
  homebrew: name=tmux
            state=present
  when: ansible_distribution == 'MacOSX'

- name: ensure tmux is installed - Ubuntu
  apt: name=tmux
       state=present
  when: ansible_distribution == 'Ubuntu'

- name: configure tmux
  template: src=tmux.conf
            dest=~/.tmux.conf
