---
- name: put script to remote
  template: src=set-settings.applescript
            dest="{{ ansible_env['TMPDIR'] }}/set-settings.applescript"

- name: put settings to remote
  copy: src="{{ item }}"
        dest="{{ ansible_env['TMPDIR'] }}/{{ item }}"
  with_items:
    - "Erning.terminal"
    - "Tomorrow Night.terminal"
    - "Tomorrow Night Bright.terminal"
  notify:
    - set terminal settings
