---
- name: ensure .vim directory is ready
  file: path={{ item }}
        state=directory
        recurse=yes
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle
    - ~/.vim/after/ftplugin

- name: install pathogen.vim
  get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
           dest=~/.vim/autoload/pathogen.vim

- name: install bundles
  git: repo={{ item.repo }}
       dest=~/.vim/bundle/{{ item.name }}
       update={{ update_vim_bundles }}
  with_items:
    - name: vim-colors-solarized
      repo: https://github.com/altercation/vim-colors-solarized.git
    - name: vim-tomorrow-theme
      repo: https://github.com/chriskempson/vim-tomorrow-theme.git
    - name: vim-airline
      repo: https://github.com/bling/vim-airline.git
    - name: ctrlp.vim
      repo: https://github.com/kien/ctrlp.vim.git
    - name: nerdtree
      repo: https://github.com/scrooloose/nerdtree.git
    - name: vim-gitgutter
      repo: https://github.com/airblade/vim-gitgutter.git
    - name: vim-markdown
      repo: https://github.com/plasticboy/vim-markdown.git
    - name: asciidoc-vim
      repo: https://github.com/dagwieers/asciidoc-vim.git
    - name: vim-coffee-script
      repo: https://github.com/kchmck/vim-coffee-script.git
    - name: vim-golang
      repo: https://github.com/jnwhiteh/vim-golang.git
    - name: vim-haml
      repo: https://github.com/tpope/vim-haml.git
    - name: vim-less
      repo: https://github.com/groenewege/vim-less.git
    - name: nginx-vim-syntax
      repo: https://github.com/evanmiller/nginx-vim-syntax.git
    - name: Vim-Jinja2-Syntax
      repo: https://github.com/Glench/Vim-Jinja2-Syntax.git
    - name: vim-cucumber
      repo: https://github.com/tpope/vim-cucumber.git
    - name: vcl-vim-plugin
      repo: https://github.com/smerrill/vcl-vim-plugin.git

- name: configure .vimrc
  template: src=vimrc
            dest=~/.vimrc

- name: copy files
  copy: src={{ item }}
        dest=~/.vim/{{ item }}
  with_items:
    - after/ftplugin/html.vim
    - after/ftplugin/ruby.vim
    - after/ftplugin/yaml.vim
    - after/ftplugin/php.vim
