---
- name: ensure avatars directory is ready
  file: path={{ avatars_directory }}
        state=directory
        recurse=yes

- name: copy avatars
  copy: src=erning-avatar.png
        dest={{ avatars_directory }}
